name: Update History

on:
  schedule:
    - cron: '*/3 * * * *' # Mỗi 5 phút
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install node-fetch
        run: npm install node-fetch@2
      - name: Run update script
        run: node update-history.js
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add history.json
          git commit -m 'Update history.json [bot]' || echo 'No changes to commit'
          git push
